name: BUILD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ðŸ›  Build and publish to private registery
    runs-on: ubuntu-latest
    steps:
      - name: Login to private registery
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTERY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout repo
        if: success()
        uses: actions/checkout@master

      - name: Automated Version Bump
        if: success()
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker container
        if: success()
        run: docker build . -t ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_nest_data_collector_service

      - name: Push docker container to private registery
        if: success()
        run: docker push ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_nest_data_collector_service

      - name: Slack Notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: github_builds
          SLACK_USERNAME: 'Github CI'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars2.githubusercontent.com/u/25100863?s=40&v=4
          SLACK_TITLE: Build status
          SLACK_MESSAGE: 'Build failed  :bangbang:'
          SLACK_COLOR: '#ff0000'

      - name: Slack Notification on sucess
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: github_builds
          SLACK_USERNAME: 'Github CI'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars2.githubusercontent.com/u/25100863?s=40&v=4
          SLACK_TITLE: Build status
          SLACK_MESSAGE: 'Build passed  :rocket:'
